### ISSUE TITLE
Capture classpath isolation / runner approach in rationale

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc-analyzer#16]
A big part of the cljdoc analyzer project is setting up the classpath for the project under analysis. Doing this the cljdoc analyzer:

- comes without any dependencies that might affect dependency resolution and 
- handles common issues around project dependencies in the [`deps` namespace](https://github.com/cljdoc/cljdoc-analyzer/blob/1e3fe4cb5a548f25495d671502325d3407712fc1/src/cljdoc_analyzer/deps.clj)

I think these things are worth capturing in the rationale as they are responsible for a much of the code beyond the metagetta module that actually extracts API information.

**Comment by lread** [comment]
I do see that I touched on this much later in the docs under [internal workings](https://github.com/cljdoc/cljdoc-analyzer/blob/master/README.adoc#internal-workings).

If you feel a summarizing this in the rationale still makes sense, lemme know, and I'll do it.

**Comment by lread** [comment]
Actually... maybe a little overview diagram near the top of the doc would help to drive the point home?
