### ISSUE TITLE
Running Tests is Taking Longer

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc-analyzer#37]
While @holyjak and I were investigating an issue we noticed that test times have been creeping significantly upward over the last 10 months.

As of 9-Feb-2021 (builds are randomly picked and do not at all imply cause):

* 10 months ago a [build was taking 4-ish minutes](https://app.circleci.com/pipelines/github/cljdoc/cljdoc-analyzer/90/workflows/8bcb91d6-c46c-486d-8458-f885a88266fe/jobs/90).
* 9 months ago [7-ish minutes](https://app.circleci.com/pipelines/github/cljdoc/cljdoc-analyzer/104/workflows/6774e768-a02a-489d-b408-99b93b5a5334/jobs/105)
* and since 8 months ago we seem to be [around 10-ish minutes](https://app.circleci.com/pipelines/github/cljdoc/cljdoc-analyzer/120/workflows/0f3441c9-df93-43a4-838a-c5df12859c65/jobs/121)

My guess is that we've simply added more integration tests and integration tests take a while to run.
I've created this issue as a reminder to check if that is true.

**Comment by holyjak** [comment]
FYI on my machine, 16 out of the 19 min of testing were in `cljdoc-analyzer.cljdoc-main-shell-test` and over 2 min in `cljdoc-analyzer.main-shell-test`. The 3 slowest tests:

```
Top 3 slowest kaocha.type/var (363.75699 seconds, 33.0% of total time)
  cljdoc-analyzer.cljdoc-main-shell-test/gorilla-ui-remotely
    151.37485 seconds cljdoc_analyzer/cljdoc_main_shell_test.clj:147
  cljdoc-analyzer.cljdoc-main-shell-test/cli-matic-remotely
    118.48539 seconds cljdoc_analyzer/cljdoc_main_shell_test.clj:140
  cljdoc-analyzer.cljdoc-main-shell-test/re-frame-remotely
    93.89674 seconds cljdoc_analyzer/cljdoc_main_shell_test.clj:60
```

**Comment by lread** [comment]
If we want to study a lib that takes a while to import [sicmutils](https://github.com/sicmutils/sicmutils) (v0.18.0 at the time of this writing) is a good candidate 
Just finished bumping cljdoc timeout for CircleCI analysis jobs from 5min to 10min to accommodate it: https://github.com/cljdoc/cljdoc/issues/447.

**Comment by lread** [comment]
I had a peek at sicmutils and found that we are slow at analyzing cljs files.

I think this is because we are recreating our cljs compilation environment for each and every cljs source file instead of reusing it. This means the cljs analyzer isn't able to take advantage of any caching and all referenced namespaces have to be re-analyzed for every cljs file.

A hacky little test on my dev box is showing sicmutils analysis taking
1. pre-hack 4m48s
2. post-hack 41s

I'll follow up with a proper fix.

**Comment by holyjak** [comment]
Awesome!

**Comment by lread** [comment]
This commit should help a bit too: db77160c737ae2290264065ba9b1d2f8609409a6

**Comment by lread** [comment]
So looked at old builds I referenced in this issue

*  [An April 2020 build was taking 4-ish minutes](https://app.circleci.com/pipelines/github/cljdoc/cljdoc-analyzer/90/workflows/8bcb91d6-c46c-486d-8458-f885a88266fe/jobs/90). Integration tests for 11 libs.

* [A May 2020 build was taking 7-ish minutes](https://app.circleci.com/pipelines/github/cljdoc/cljdoc-analyzer/104/workflows/6774e768-a02a-489d-b408-99b93b5a5334/jobs/105). Integration tests for 13 libs.

*  [A June 2020 build was taking around 10-ish minutes](https://app.circleci.com/pipelines/github/cljdoc/cljdoc-analyzer/120/workflows/0f3441c9-df93-43a4-838a-c5df12859c65/jobs/121). Integration tests for 16 libs.

So we did have some specific and important optimizations to make, but the number an increasing number of libs we are integration testing is the current main contributor.

@holyjak waddya think? Close this issue and create a new issue if we want to revisit slow tests in the future?

**Comment by holyjak** [comment]
Yes, do it! Great job!
