### ISSUE TITLE
Decide what to do with shared-utils

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc-analyzer#9]
Currently some namespaces from cljdoc's [shared-utils](https://github.com/cljdoc/cljdoc/tree/master/modules/shared-utils) module are copied here. This means some code is duplicated and could get out of sync (not too likely or regularly but still possible).

Could we include shared-utils via a git dependency?

**Comment by lread** [comment]
There is some risk but the code is so small, I'm not concerned about the duplication.

**Comment by lread** [comment]
Yeah, turns out you were right @martinklepsch, it is confusing.
I'll think of something.

**Comment by lread** [comment]
I think I originally punted on this because I did not want to take on the task of fully understanding the shared code.

A full understanding would be ideal, but is not a pre-requisite.

**Comment by lread** [comment]
Here's my current thinking:
- create a new project `cljdoc/cljdoc-shared`.
- add a clear README as to the project's purpose
- understand what is really shared, adjust cljdoc as necessary (some code under `modules/shared-utils` are only used by cljdoc)
- move shared code into `cljdoc/cljdoc-shared`.
- reference `cljdoc-shared` from `cljdoc-analyzer` and `cljdoc` via git dep.

Other options:
- use git modules - this might be more confusing than it is worth for a library I expect to change relatively rarely

Watcha think @martinklepsch (and anyone else lurking/interested!).

**Comment by lread** [comment]
Another option might be to consider a [monorepo](https://corfield.org/blog/2021/02/23/deps-edn-monorepo/). 
Not sure if it applies, but could be interesting to explore if the current scheme proves to be a burden.
